# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.message_generator:
        class: AppBundle\Service\UsuarioService
        arguments: ['@logger']