<?php

namespace BibliotecaBundle\Repository;

/**
 * EditoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditoraRepository extends \Doctrine\ORM\EntityRepository
{
}
