<?php

namespace Employees\Bundle\EmployeesBundle\Repository;

/**
 * EmployeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeesRepository extends \Doctrine\ORM\EntityRepository
{
}
