<?php

namespace Casa\Bundle\QuartoBundle\Repository;

/**
 * MoveisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveisRepository extends \Doctrine\ORM\EntityRepository
{
	public function teste(){
		return array(1);
	}
}
