app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /app

store:
    resource: "@StoreBundle/Controller/"
    type:     annotation
    prefix:   /store

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"